# Generated by Django 6.0 on 2026-01-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to='ideas/')),
                ('content', models.TextField()),
                ('interest', models.IntegerField()),
                ('devtool', models.CharField(max_length=200)),
            ],
        ),
    ]
