# Generated by Django 6.0 on 2026-01-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_devtool'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
