# Generated by Django 6.0 on 2026-01-02 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
