# Generated by Django 5.2.4 on 2026-01-14 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('region', models.CharField(max_length=20, verbose_name='지역')),
                ('price', models.IntegerField(default=1000, verbose_name='가격')),
                ('photo', models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name='이미지')),
                ('nutrition_photo', models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name='영양 성분 이미지')),
                ('kcal', models.FloatField(blank=True, default=0, null=True, verbose_name='칼로리')),
                ('carbohydrate', models.FloatField(blank=True, default=0, null=True, verbose_name='탄수화물(g)')),
                ('protein', models.FloatField(blank=True, default=0, null=True, verbose_name='단백질(g)')),
                ('fat', models.FloatField(blank=True, default=0, null=True, verbose_name='지방(g)')),
                ('sort_hashtag', models.CharField(blank=True, max_length=50, verbose_name='상품 종류 해시 태그')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='작성자')),
            ],
        ),
    ]
