# Generated by Django 6.0 on 2025-12-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('actor', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('runtime', models.IntegerField()),
                ('release_year', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
