# Generated by Django 5.2.4 on 2026-01-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='review',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(choices=[('tmdb', 'TMDB'), ('manual', '직접 추가')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
